In [1]:
#Written Problems

Problem 4.2.9\
$UU ^ {-1} = I$\
Assume $V=U^{-1}$\
Iterate i from n to 1\
&nbsp;&nbsp;&nbsp;&nbsp;$v_{ii} = \frac{1}{u_{ii}}$\
&nbsp;&nbsp;&nbsp;&nbsp;Iterate j from i-1 to 1\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$v_{ji} = \frac{-\sum_{k=j+1}^i u_{jk}v_{ki}}{u_{jj}}$
end

Problem 4.2.19\
$A=LU$\
$A^{-1} = (LU)^{-1}$\
$A^{-1} = U^{-1}L{-1}$\
say $U^{-1} = M$ and $L^{-1} = N$\
Iterate i from n to 1\
&nbsp;&nbsp;&nbsp;&nbsp;$m_{ii} = \frac{1}{u_{ii}}$\
&nbsp;&nbsp;&nbsp;&nbsp;Iterate j from i-1 to 1\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$m_{ji} = \frac{-\sum_{k=j+1}^i u_{jk}m_{ki}}{u_{jj}}$\
end\
Iterate i from 1 to n\
&nbsp;&nbsp;&nbsp;&nbsp;$n_{ii} = \frac{1}{l_{ii}}$\
&nbsp;&nbsp;&nbsp;&nbsp;Iterate j from i+1 to n\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$n_{ji} = \frac{-\sum_{k=i}^{j-1} l_{jk}v_{ki}}{l_{jj}}$\
end\
Now we got both M and N\
We can do $A^{-1} = MN$

Problem 4.2.22\
This is correct\
$x_i$ will essentially be $x_i = \frac{b_{i}-\sum_{j=i+1}^n u_{ij}x_j}{u_{ii}}$\
This algorithm is basically doing $\frac{b_{i}}{u_{ii}}$ first\
Then it changes $b_{i}$ for next loops, where all the $b_{i}$s will be subtracted by current j of $u_{ij}x_j$\
So that when it's looped to the current $b_{i}$, it's already subtracted by the necessary terms, so it's safe to do $\frac{b_{i}}{u_{ii}}$

Problem 4.2.30\
Say all $l_{ii} = 1$\
By doing algorithm\
$$
L = \left(\begin{array}{cc} 
1 & 0 & 0\\
\frac{a_{21}}{u_{11}} & 1 &0 \\
\frac{a_{31}}{u_{11}} & \frac{a_{32}-l_{31}u_{12}}{u_{22}} & 1
\end{array}\right) =
\left(\begin{array}{cc} 
1 & 0 & 0\\
0 & 1 &0 \\
\frac{1}{3} & -3 & 1
\end{array}\right)
$$
$$
U = \left(\begin{array}{cc} 
\frac{a_{11}}{l_{11}} & \frac{a_{12}}{l_{11}} & \frac{a_{13}}{l_{11}}\\
0 & \frac{a_{22}-l_{21}u_{12}}{l_{22}} & \frac{a_{23}-l_{21}u_{13}}{l_{22}} \\
0 & 0 & \frac{a_{33}-l_{31}u_{13}-l_{32}u_{23}}{l_{33}}
\end{array}\right)=
\left(\begin{array}{cc} 
3 & 0 & 1\\
0 & -1 & 3 \\
0 & 0 & \frac{26}{3}
\end{array}\right)
$$ 


Probelm 3.2.31\
$$L = \left(\begin{array}{cc} 
(a_{11})^{\frac{1}{2}} & 0\\
\frac{a_{21}}{l_{11}} & (a_{22} - l_{21}^2)^{\frac{1}{2}}
\end{array}\right)
=\left(\begin{array}{cc} 
1 & 0\\
2 & 1
\end{array}\right)$$

Probelm 3.2.32\
$$L = \left(\begin{array}{cc} 
(a_{11})^{\frac{1}{2}} & 0 & 0\\
\frac{a_{21}}{l_{11}} & (a_{22} - l_{21}^2)^{\frac{1}{2}} & 0 \\
\frac{a_{31}}{l_{11}} & \frac{a_{32}-l_{21}l_{31}}{l_{22}} & ({a_{33}-l_{31}^2-l_{32}^2})^{\frac{1}{2}}
\end{array}\right)
=\left(\begin{array}{cc} 
2 & 0 & 0\\
\frac{1}{4} & 1 & 0 \\
\frac{1}{2} & \frac{1}{8} & \frac{{1}}{2}
\end{array}\right)$$

Probelm 3.2.36\
Say all $l_{ii} = 2$\
By doing algorithm\
$$
L = \left(\begin{array}{cc} 
2 & 0 & 0\\
\frac{a_{21}}{u_{11}} & 2 &0 \\
\frac{a_{31}}{u_{11}} & \frac{a_{32}-l_{31}u_{12}}{u_{22}} & 2
\end{array}\right) =
\left(\begin{array}{cc} 
2 & 0 & 0\\
4 & 2 & 0 \\
0 & 3 & 2
\end{array}\right)
$$
$$
U = \left(\begin{array}{cc} 
\frac{a_{11}}{l_{11}} & \frac{a_{12}}{l_{11}} & \frac{a_{13}}{l_{11}}\\
0 & \frac{a_{22}-l_{21}u_{12}}{l_{22}} & \frac{a_{23}-l_{21}u_{13}}{l_{22}} \\
0 & 0 & \frac{a_{33}-l_{31}u_{13}-l_{32}u_{23}}{l_{33}}
\end{array}\right)=
\left(\begin{array}{cc} 
3 & 5 & 0\\
0 & 3 & 2 \\
0 & 0 & 3
\end{array}\right)
$$ 

Probelm 3.2.46\
\begin{eqnarray}
x^TA=b^T\\
x^TLU=b^T\\
U^TL^Tx=b
\end{eqnarray}
Assume$z=L^Tx$\
Then $U^Tz=b$\
Solve $z_i$\
Interate i from 1 to n\
&nbsp;&nbsp;&nbsp;&nbsp;$z_i = \frac{b_i-\sum_{j=1}^{i-1}u_{ji}z_j}{u_{ii}}$\
end\
Solve $x_i$\
Interate i from n to 1\
&nbsp;&nbsp;&nbsp;&nbsp;$x_i = \frac{z_i-\sum_{j=1}^{i-1}l_{ji}x_j}{l_{ii}}$\
end\
X is solved

In [2]:
#Computer Problems

In [3]:
#Problem 4.1.2
import numpy as np
#a. Store function
def store(n, x, y):
    # Create a copy of the elements in array x and store it in y
    y = np.copy(x)  # Copy the contents of array x into array y
    return y        # Return the modified y

#b. Matrix-vector product function
def prod(m, n, A, x, y):
    # Iterate over each row of matrix A
    for i in range(m):
        y[i] = 0  # Initialize y[i] as 0 for the result of the dot product
        # Compute the dot product of the i-th row of A with vector x
        for j in range(n):
            y[i] += A[i][j] * x[j]  # Multiply and accumulate A[i][j] and x[j]
    
    return y  # Return the resulting vector y
# c. Matrix-matrix multiplication function
def mult(k, m, n, A, B, C):
    # Matrix A has size k x m, Matrix B has size m x n, Matrix C will be k x n
    for i in range(k):  # Iterate over rows of A
        for j in range(n):  # Iterate over columns of B
            C[i][j] = 0  # Initialize the element of matrix C at position [i][j]
            for l in range(m):  # Iterate over columns of A and rows of B
                C[i][j] += A[i][l] * B[l][j]  # Matrix multiplication formula
    return C
# d. Dot product function
def dot(n, x, y, a):
    # Compute the dot product of two vectors x and y, adding the result to a
    for i in range(n):  # Iterate over all elements in vectors x and y
        a += x[i] * y[i]  # Add the product of corresponding elements to a
    return a  # Return the updated value of a

In [4]:
#Problem 4.2.1

# Function to compute the inverse of a lower triangular matrix L
def computeInverseL(L):
    # Initialize V as an empty matrix of the same shape as L to store the inverse
    V = np.zeros_like(L, dtype=float)
    n = len(L)
    
    # Loop through rows of L to compute diagonal and off-diagonal elements of V
    for i in range(n):
        # Inverse of the diagonal element L[i][i]
        V[i][i] = 1 / L[i][i]
        
        # Compute the off-diagonal elements of the inverse matrix V
        for j in range(i + 1, n):
            sum = 0
            # Summing over already calculated elements of V and L for inversion
            for k in range(j):
                sum += V[k][i] * L[j][k]
            # Calculate the off-diagonal element
            V[j][i] = -sum / L[j][j]
    
    return V

# Initialize a 10x10 lower triangular matrix L
L = np.zeros((10, 10), dtype=float)

# Populate L with values: (i + j)^2 for all elements where i >= j
for i in range(1, 11):
    for j in range(1, 11):
        if i >= j:
            L[i - 1][j - 1] = float((i + j)**2)

# Print the matrix L
print(L)

# Compute the inverse of L using the custom function
inverseL = computeInverseL(L)

# Print the product of L and its inverse to verify if it results in an identity matrix
# with options to format the output (2 decimal precision, no scientific notation)
with np.printoptions(precision=2, suppress=True):
    print(L @ inverseL)

[[  4.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  9.  16.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 16.  25.  36.   0.   0.   0.   0.   0.   0.   0.]
 [ 25.  36.  49.  64.   0.   0.   0.   0.   0.   0.]
 [ 36.  49.  64.  81. 100.   0.   0.   0.   0.   0.]
 [ 49.  64.  81. 100. 121. 144.   0.   0.   0.   0.]
 [ 64.  81. 100. 121. 144. 169. 196.   0.   0.   0.]
 [ 81. 100. 121. 144. 169. 196. 225. 256.   0.   0.]
 [100. 121. 144. 169. 196. 225. 256. 289. 324.   0.]
 [121. 144. 169. 196. 225. 256. 289. 324. 361. 400.]]
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0. -0. -0. -0.  1.  0.  0.  0.  0.]
 [ 0. -0.  0.  0.  0. -0.  1.  0.  0.  0.]
 [ 0. -0. -0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. -0.  0. -0.  0. -0.  0.  1.  0.]
 [ 0. -0.  0. -0. -0. -0. -0. -0.  0.  1.]]


In [5]:
#Problem 4.2.2
# Initialize a symmetric matrix A
A = np.array([[5, 7, 6, 5],
              [7, 10, 8, 7],
              [6, 8, 10, 9],
              [5, 7, 9, 10]])
A = A / 100

# Function to perform Cholesky decomposition of a positive-definite matrix A
def cholesky(A):
    n = len(A)  # Size of the matrix A
    L = np.zeros_like(A, dtype=float)  # Initialize L as a zero matrix of same shape as A
    
    # Loop through rows to compute lower triangular matrix L
    for k in range(n):
        sum = 0
        # Calculate sum of squares of L elements in row k for diagonal entry
        for s in range(k):
            sum += L[k][s] ** 2
        # Compute the diagonal element L[k][k]
        L[k][k] = np.sqrt(A[k][k] - sum)
        
        # Compute the off-diagonal elements L[i][k] for rows below the diagonal
        for i in range(k + 1, n):
            sum = 0
            # Summing products of corresponding elements of L for the off-diagonal element
            for s in range(k):
                sum += L[i][s] * L[k][s]
            # Compute L[i][k] (off-diagonal entry)
            L[i][k] = (A[i][k] - sum) / L[k][k]
    
    return L

# Perform Cholesky decomposition on matrix A
L = cholesky(A)

# Transpose the lower triangular matrix L to get its transpose (L^T)
L_T = np.transpose(L)

# Compute the inverse of the lower triangular matrix L using the previously defined function
inverseL = computeInverseL(L)

# Initialize vector b as a column vector
b = np.array([[0.23],
              [0.32],
              [0.33],
              [0.31]])

# Update b by multiplying it with the inverse of L (inverseL * b)
b = inverseL @ b

# Function to solve the system L_T * x = b using back substitution
def solvex(L_T, b):
    n = len(L_T)  # Size of the matrix
    x = np.zeros(n, dtype=float)  # Initialize solution vector x with zeros
    
    # Perform back substitution, starting from the last row to the first
    for i in range(n - 1, -1, -1):
        sum = 0
        # Summing already solved variables in x
        for s in range(i + 1, n):
            sum += L_T[i][s] * x[s]
        # Solve for x[i] by isolating it in the equation
        x[i] = (b[i].item() - sum) / L_T[i][i]
    
    return x

# Solve the system L_T * x = b and print the solution vector x
print(solvex(L_T, b))


[1. 1. 1. 1.]
